Remove storage dep
gearama/azure-sdk-for-cpp pull request #1
Opened 2024-01-04 22:51 UTC by gearama

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2024-01-05 00:23 UTC, RickWinter commented on sdk/tables/azure-data-tables/src/serializers.cpp
> +#include <azure/core/internal/json/json.hpp>
```suggestion
#include <azure/core/internal/json/json.hpp>


```

2024-01-08 23:50 UTC, LarryOsterman requested changes

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core-xml/test/ut/template_test.cpp
> +using namespace Azure::Core::Xml;
TemplateTest?

Also, is there any actual test code here?

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core-xml/vcpkg.json
> +  "name": "azure-template-cpp",
Package name.

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core-xml/vcpkg.json
> +}
Missing crlf at end of file. Likely there are others too.

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core-xml/vcpkg/vcpkg.json
> +  "name": "azure-template-cpp",
azure-template?

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +        : AccountName(std::move(accountName)), m_accountKey(std::move(accountKey))
In general, we prefer initializer syntax (`AccountName{std::move(accountName))`) over call syntax (`AccountName(std::move(accountName))`). That's because the call syntax is ambiguous - you don't know if it's a member initialization or a call to a method named AccountName.

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +  namespace _internal {
I'm concerned about how heavily storage affiliated this is. Azure Core should be generic and shouldn't have explicit service specific elements. 

Does a connection string really contain 5 different service URLs? Or could it be a single URL?

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core/src/credentials/shared_key_credential.cpp
> +    endpoint = getWithDefault(connectionStringMap, "TableEndpoint");
This is really concerning because this is an azure core component that has a VERY hard dependency on the service implementation. 

Is there a way of refactoring this code to move the connection string information to the service implementation? Possibly by parameterizing the various elements and moving that to the caller?

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core/src/cryptography/hmacsha256.cpp
> +}}} // namespace Azure::Core::Cryptography
Missing crlf at end - not going to flag others.

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core/inc/azure/core/http/policies/per_retry_policy.hpp
> +  class PerRetryPolicy final : public Core::Http::Policies::HttpPolicy {
This doesn't appear to be a per-retry policy. It appears to be a request timeout policy which is instantiated in the per-retry part of the pipeline.

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +  class SharedKeyCredential final {
Will this implementation work for non-storage shared keys? Specifically, I'm wondering about EventHubs and KeyVault shared keys.

If it *is* storage specific (the source was `StorageSharedKeyCredential`, which makes me skeptical), then is there a way of isolating the key generation logic to something which can be plugged in so that the implementation no longer is storage specific?

2024-01-08 23:50 UTC, LarryOsterman commented on sdk/tables/azure-data-tables/src/tables_clients.cpp
> -  perRetryPolicies.emplace_back(std::make_unique<_internal::StoragePerRetryPolicy>());
Should these policies be moved to azure core, or should they simply be cloned into the tables implementation? Most of them are sufficiently simple that I'm not concerned about the duplicated code. But I *AM* concerned about adding a significant amount of what is effectively storage-only code into azure core.

2024-01-09 00:06 UTC, gearama commented on sdk/core/azure-core-xml/inc/azure/core/xml/template_client.hpp
> +    TemplateClient(TemplateClientOptions const& options = TemplateClientOptions{});
oops , thank you for catching this leftover file

2024-01-09 00:08 UTC, gearama commented on sdk/core/azure-core-xml/inc/azure/core/xml/xml_wrapper.hpp
> +namespace Azure { namespace Core { namespace Xml {
done

2024-01-09 00:09 UTC, gearama commented on sdk/core/azure-core-xml/inc/azure/core/xml/xml_wrapper.hpp
> +    XmlNodeType Type;
this file was copied from storage, it is now internal namespace.

2024-01-09 00:12 UTC, gearama commented on sdk/core/azure-core-xml/inc/azure/core/xml/xml_wrapper.hpp
> +    XmlReader(XmlReader&& other) noexcept { *this = std::move(other); }
no idea to be honest, the file was copied as is from storage and i tried to not change functionality in order to have the same behavior as in storage which we know works. since the file has no intrinsic tests, but relies on request/responses to perform the testing.

2024-01-09 00:13 UTC, gearama commented on sdk/core/azure-core-xml/test/ut/template_test.cpp
> +using namespace Azure::Core::Xml;
done

2024-01-09 00:21 UTC, gearama commented on sdk/core/azure-core/inc/azure/core/http/policies/per_retry_policy.hpp
> +  class PerRetryPolicy final : public Core::Http::Policies::HttpPolicy {
renamed to TimeoutPolicy

2024-01-09 00:27 UTC, gearama commented on sdk/core/azure-core-xml/vcpkg.json
> +  "name": "azure-template-cpp",
done

2024-01-09 00:27 UTC, gearama commented on sdk/core/azure-core-xml/vcpkg/vcpkg.json
> +  "name": "azure-template-cpp",
done

2024-01-09 00:28 UTC, gearama commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +        : AccountName(std::move(accountName)), m_accountKey(std::move(accountKey))
i don't see the diffrence between (AccountName{std::move(accountName))) and (AccountName(std::move(accountName))) it's the same thing

2024-01-09 01:32 UTC, gearama commented on sdk/tables/azure-data-tables/src/tables_clients.cpp
> -  perRetryPolicies.emplace_back(std::make_unique<_internal::StoragePerRetryPolicy>());
i moved them to tables

2024-01-09 01:37 UTC, gearama commented on sdk/core/azure-core/src/credentials/shared_key_credential.cpp
> +    endpoint = getWithDefault(connectionStringMap, "TableEndpoint");
moved to tables toghether with the policies to which it belongs

2024-01-09 01:37 UTC, gearama commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +  class SharedKeyCredential final {
moved to tables with the policies to which it belongs

2024-01-09 01:38 UTC, gearama commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +  namespace _internal {
they are named diffrently for each service

2024-01-09 01:50 UTC, gearama commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +        : AccountName(std::move(accountName)), m_accountKey(std::move(accountKey))
OMG curly brace vs paran, done, the font IE is using shows no difference unless i look really close to the screen, also you did not close the curly  , just opened it 
i had to put it in notepad to see the difference

2024-01-09 17:38 UTC, LarryOsterman commented on sdk/core/azure-core/inc/azure/core/credentials/shared_key_credential.hpp
> +        : AccountName(std::move(accountName)), m_accountKey(std::move(accountKey))
Oops. Sorry about that. And yeah, it's REALLY hard to see.

2024-01-09 17:41 UTC, LarryOsterman commented on sdk/core/azure-core-xml/inc/azure/core/xml/xml_wrapper.hpp
> +    XmlReader(XmlReader&& other) noexcept { *this = std::move(other); }
That makes complete sense to me.

2024-01-09 17:42 UTC, LarryOsterman commented on sdk/core/azure-core-xml/inc/azure/core/xml/xml_wrapper.hpp
> +    XmlNodeType Type;
Thank you - we *really* don't want to expose an XML API surface, *especially* this XML API surface :).

2024-01-09 22:13 UTC, RickWinter commented on sdk/core/azure-core-xml/inc/azure/core/xml/dll_import_export.hpp
> +}}} // namespace Azure::Core::Xml
```suggestion
}}} // namespace Azure::Core::Xml

```

2024-01-09 22:13 UTC, RickWinter commented on sdk/core/azure-core-xml/vcpkg.json
> +}
```suggestion
}

```

2024-01-09 22:13 UTC, RickWinter commented on sdk/tables/azure-data-tables/inc/azure/data/tables.hpp
> +#include "azure/data/tables/policies/timeout_policy.hpp"
```suggestion
#include "azure/data/tables/policies/timeout_policy.hpp"

```

2024-01-09 22:29 UTC, RickWinter commented on sdk/core/azure-core/src/cryptography/hmacsha256.cpp
> +// Copyright (c) Microsoft Corporation.
If customers won't be using this, it should be internal or in tables package.

2024-01-09 22:31 UTC, RickWinter commented on sdk/core/azure-core-xml/src/private/package_version.hpp
> +namespace Azure { namespace Core { namespace Xml { namespace _detail {
namespace Azure { namespace Core { namespace _internal { namespace Xml {

2024-01-09 22:33 UTC, RickWinter commented on sdk/core/azure-core/CMakeLists.txt
> +add_library(azure-core ${AZURE_CORE_HEADER} ${AZURE_CORE_SOURCE} "src/cryptography/hmacsha256.cpp")
This line is unnecessary.

2024-01-09 22:38 UTC, RickWinter commented on sdk/tables/azure-data-tables/src/policies/tenant_bearer_token_policy.cpp
> +namespace Azure { namespace Data { namespace Tables { namespace _internal { namespace Policies {
These are _details

2024-01-09 22:46 UTC, RickWinter commented on sdk/core/azure-core/CMakeLists.txt
> +add_library(azure-core ${AZURE_CORE_HEADER} ${AZURE_CORE_SOURCE} "src/cryptography/hmacsha256.cpp")
```suggestion
add_library(azure-core ${AZURE_CORE_HEADER} ${AZURE_CORE_SOURCE})
```

2024-01-09 22:51 UTC, gearama commented on sdk/tables/azure-data-tables/src/policies/tenant_bearer_token_policy.cpp
> +namespace Azure { namespace Data { namespace Tables { namespace _internal { namespace Policies {
done

2024-01-09 23:05 UTC, LarryOsterman commented on sdk/tables/azure-data-tables/inc/azure/data/tables.hpp
> +#include "azure/data/tables/policies/timeout_policy.hpp"
Missing crlf at end of file (thank you github for letting me see these easily :)).

2024-01-09 23:10 UTC, LarryOsterman approved these changes

2024-01-09 23:10 UTC, LarryOsterman commented on sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/shared_key_credential.hpp
> +   * @brief Gets the name of the Account.
```suggestion
   * @brief The name of the Account.
```

A major nit: Because this is *not* a method, it cannot take any action (like "Get").

2024-01-09 23:12 UTC, gearama commented on sdk/core/azure-core/CMakeLists.txt
> +add_library(azure-core ${AZURE_CORE_HEADER} ${AZURE_CORE_SOURCE} "src/cryptography/hmacsha256.cpp")
done

2024-01-09 23:13 UTC, gearama commented on sdk/tables/azure-data-tables/inc/azure/data/tables/credentials/shared_key_credential.hpp
> +   * @brief Gets the name of the Account.
done

2024-01-09 23:15 UTC, gearama commented on sdk/core/azure-core/CMakeLists.txt
> +add_library(azure-core ${AZURE_CORE_HEADER} ${AZURE_CORE_SOURCE} "src/cryptography/hmacsha256.cpp")
done

2024-01-09 23:22 UTC, gearama commented on sdk/core/azure-core/src/cryptography/hmacsha256.cpp
> +// Copyright (c) Microsoft Corporation.
done

2024-01-09 23:39 UTC, merged